# Generated by Django 5.2.17 on 2026-08-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_type', models.CharField(choices=[('PER_HOUR', 'Per Hour'), ('FLAT', 'Flat Fee')], default='FLAT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='Wrench', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('room_type', models.CharField(choices=[('PODCAST', 'Podcast Studio'), ('BROADCAST', 'Broadcast Presentation Suite'), ('MULTI_CAM', 'Multi-Camera Video Stage'), ('AUDIO_MASTER', 'Audio Mastering & Voiceover')], default='PODCAST', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('half_day_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('full_day_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_capacity', models.PositiveIntegerField(default=4)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('acoustics_rating', models.CharField(default='STC-60 Sound Isolation', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('MIC', 'Microphone'), ('CAM', '4K Camera / Lens'), ('LIGHT', 'Lighting System'), ('AUDIO', 'Audio Interface / Mixer'), ('OTHER', 'Accessory / Teleprompter')], max_length=50)),
                ('model_spec', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='studios.studioroom')),
            ],
        ),
    ]
