# Generated by Django 5.2.17 on 2026-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studioroom',
            name='image_url',
        ),
        migrations.AddField(
            model_name='studioroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studios/'),
        ),
    ]
