# Generated by Django 4.2 on 2026-09-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_delete_bookingaddon'),
        ('studios', '0002_remove_studioroom_image_url_studioroom_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddOnService',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
