# Generated by Django 5.2.17 on 2026-09-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_blog_image_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('NORMAL', 'Normal'), ('COMING_SOON', 'Coming Soon'), ('MAINTENANCE', 'Maintenance')], default='NORMAL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
