# Generated by Django 4.2 on 2026-09-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_expires_at_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cashfree_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
