# Generated by Django 4.2 on 2026-09-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cashfree_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingAddOn',
        ),
    ]
