databases:
  - name: studioplus-db
    plan: free
    databaseName: studioplus
    user: studioplus

services:
  - type: web
    name: studioplus-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studioplus-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://studio-floor.vercel.app,http://localhost:3000" # Update when custom domain is set
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
